# Generated by Django 5.1.6 on 2025-04-05 13:52

import user_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=user_auth.models.private_media_path),
        ),
        migrations.AlterField(
            model_name='message',
            name='encrypted_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
