# Generated by Django 5.1.6 on 2025-04-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_message_media_alter_message_encrypted_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='expires_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='is_ephemeral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='expires_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_ephemeral',
            field=models.BooleanField(default=False),
        ),
    ]
