# Generated by Django 5.1.6 on 2025-04-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_relationship_status_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='message_media/'),
        ),
    ]
